### PR TITLE
feat: add provider_payment_methods to billing configurations

### PR DESCRIPTION
**Pull request by willymwai**
Add provider_payment_methods field to the CustomerBillingConfiguration model

## Pull Request template

Please, go through these steps before you submit a PR.

1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:

   a. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/issue-templates`.

   b. You have a descriptive commit message with a short title (first line).

   c. You have only one commit (if not, squash them into one commit).

   d. `python3 -m pytest tests` doesn't throw any error. If it does, fix them first and amend your commit (`git commit --amend`).

3. **After** these steps, you're ready to open a pull request.

   a. Give a descriptive title to your PR.

   b. Describe your changes.

   c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

   d. Add the corresponding labels to your pull request (ex: feature, improvement, bug...)

IMPORTANT: Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.

**PLEASE REMOVE THIS TEMPLATE BEFORE SUBMITTING**

### CODE REVIEW

**Comment by rsempe** [comment]
Thanks @willymwai for this PR 👍 

Looks good to me, just minor comments related to tests:
- Can you add it into the `customer.json` [fixture](https://github.com/getlago/lago-python-client/blob/main/tests/fixtures/customer.json#L29)?
- Can you support it into the [test customer client](https://github.com/getlago/lago-python-client/blob/main/tests/test_customer_client.py)?

**Comment by willymwai** [comment]
@rsempe Thanks the comment, worked on it.

**Review by rsempe — APPROVED** [review]

**Comment by rsempe** [comment]
@willymwai It's available on the [latest version](https://pypi.org/project/lago-python-client/) 🚀

**Comment by willymwai** [comment]
Awesome 🎉

**Pull request merged**
